---
title: "Relativistic Cosmology Part 2"
author: "Dr Vicky Scowcroft"
date: "Semester 2, 2020/21"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    css: [mystyle.css]
    includes:
      # in_header: header.html
bibliography: [book.bib, packages.bib]
documentclass: book
classoption: 
 - a4paper
biblio-style: apalike
link-citations: yes
github-repo: PH40112_rmd
description: "PH40112 Relativistic Cosmology Part 2."
citecolor: magenta
filecolor: black
linkcolor: black
urlcolor: magenta
fontsize: 11pt
subparagraph: yes
#abstract: | 

---
# Unit Overview {-}
  The aim of this section of PH40112 is to present the observations and
  theory underpinning modern Cosmology. It is complementary to the first
  half of PH40112, which focusses on General Relativity and its
  applications to Cosmology. At the end of this course, you should be
  able to describe the key ideas of Cosmology, comparing and contrasting
  different observational techniques and Cosmological models. You should
  understand the implications for the fate of the Universe arising from
  these different models, and discuss the open questions being addressed
  by current state of the art experiments. You should also be able to
  assess how systematic errors and experimental uncertainties affect
  cosmological experiments, in particular how these affect our ability
  to discriminate between different models of the Universe's evolution.
  

## Suggested textbook {-}
  This section of the course closely follows several chapters of *An
  Introduction to Modern Cosmology: 3<sup>rd</sup> edition* by Liddle.
  You may find it helpful to refer to this book or others such as *The
  Oxford companion to Cosmology* by Liddle and Loveday, which is
  available in the University library.
  
## Lecture notes {-}
The lecture notes are all contained on these pages in html format. They should be accessbile from any device and should work with a screen reader. If you have difficulty accessing the notes please let me know. If you want a PDF copy of these notes you can press the PDF button in the tool bar at the top of the screen, or print each section to PDF directly from your browser. Due to the way the notes are compiled the PDF download will be formatted differently to the html pages and is provided for convenience only. 

While every effort is made to ensure the notes are correct, please let me know if you find any typos. If any changes are made to the notes during the course I will list any changes at the top of the relevant section.

## Edits to lecture notes {-}
The following sections have been edited from the initial version:

Sec \@ref(ch:eqs-of-expanding) - updated on 21/3/21 to fix incorrect signs in Eqs \@ref(eq:ric-ii) and \@ref(eq:ric-scal).

Sec \@ref(ch:dark-matter) - updated on 19/4/21 to add additional material covered in lecture recording.

Sec \@ref(ch:inflation) - updated on 25/4/21 to fix formatting and final value for the amount of expansion during inflation. 

Sec \@ref(ch:current-research) and \@ref(ch:evolving) added following discussion session on 29th April. 

## Schedule {-}
Lectures videos for this section of the course will be available on Moodle by 9am each week.

LOIL sessions will be held on Zoom on **Thursdays at 2:15pm**. These sessions are to consolidate the course material, and will be a combination of problems classes and discussion sessions. These are designed to be interactive, and you are expected to attend and participate in these sessions. We can cover material from any part of this half of the course, so please don't feel like you can't attend a LOIL if you haven't watched that week's lectures yet - questions are welcome on any of the material! 

In addition to the Thursday LOIL sessions, I will be holding optional office hours on **Mondays at 3:15pm**. These sessions are optional and will not be recorded. You are welcome to attend these sessions to ask any questions about the course material. You are also welcome to post questions on the Moodle forum or, if you would rather ask anonymously, you can post questions on this [Google Sheet](https://docs.google.com/spreadsheets/d/1QtkblLWIQ7LzWiUlu-3b3iUtGuyfQ2Qb31jY6UdCznE/edit?usp=sharing).
The planned schedule for when sections will be covered is as follows:

| Week | w/c  | Section                                    |
|:------|:------:|:--------------------------------------------|
| 6    | 8/3  | 1: [Introduction to Observational Cosmology](#ch:intro_obs) |
| 7    | 15/3 | 2: [Equations of the Expanding Universe](#ch:eqs_of_expanding)     |
|      |      | 3: [Composition of the Universe](#ch:constituents)                |
| 8    | 22/3 | 4: [Cosmological parameters](#ch:obs-params)            |
|      |      | 5: [Dark matter and dark energy](#ch:dark-matter)            |
|      | 29/3 | **Easter Break**                           |
|      | 5/4  | **Easter Break**                           |
| 9    | 12/4 | 6: [Observational techniques 1](#ch:obs-techs)             |
|      |      | 7: [Observational techniques 2](#ch:obs-techs-cmb)              |
| 10   | 19/4 | 8: [The $\Lambda$CDM Model](#ch:lambdacdm)                      |
|      |      | 9: [Inflation](#ch:inflation)                               |
| 11   | 26/4 | 10: [Current research](#ch:current-research)                      |
|      |      | 11: [The evolving Universe](#ch:evolving)                 |

## Research discussion session - **Thursday 29^th^ April 2021 2:15pm** {-}

Scientific papers often don't come to a definitive conclusion (other than "we need more data...."). The aim of this session is for you to develop your skills in interpreting scientific results, understand how they can be compared with other results, and what problems and uncertainties are related to the experiments. In this live session we will be discussing a selection of recent journal articles which use different observational techniques to measure cosmological parameters. In advance of the session you will each be assigned one of three papers to read and given guidance on what to look out for while you're reading. Further details about this session will be given closer to the time.

Some of what is discussed in this session will be summarised Section \@ref(ch:current-research). However, there is a lot of research that shows that people understand a topic better after explaining and discussing it with someone else; I've designed the session this way so you can develop a deeper understanding of the topic's we're covering. 



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
